In [2]:
import numpy as np

In [ ]:
[[0 3 0 7 0 6 9 8 4]
 [0 0 6 3 0 0 2 0 7]
 [0 0 8 0 0 0 6 0 3]
 [0 9 0 0 7 0 8 3 0]
 [8 1 0 0 6 0 7 4 5]
 [3 0 7 8 4 0 1 9 0]
 [0 0 0 0 5 4 3 7 8]
 [5 8 2 0 3 0 0 2 9]
 [0 0 0 2 8 0 5 0 0]]

[[0 3 0 7 0 6 9 8 4]
 [0 0 6 3 0 0 2 0 7]
 [0 0 8 0 0 0 6 0 3]
 [0 9 0 0 7 0 8 3 0]
 [8 1 0 0 6 0 7 4 5]
 [3 0 7 8 4 0 1 9 0]
 [0 0 0 0 5 4 3 7 8]
 [5 8 2 0 3 0 0 2 9]
 [0 0 0 2 8 0 5 0 0]]

[[0 3 0 7 0 6 9 8 4]
 [0 0 6 3 0 0 2 0 7]
 [0 0 8 0 0 0 6 0 3]
 [0 9 0 0 7 0 8 3 0]
 [8 1 0 0 6 0 7 4 5]
 [3 0 7 8 4 0 1 9 0]
 [0 0 0 0 5 4 3 7 8]
 [5 8 2 0 3 0 0 2 9] # erreur double 2 sur cette ligne
 [0 0 0 2 8 0 5 0 0]]

[[0 3 0 7 0 6 9 8 4]
 [0 0 6 3 0 0 2 0 7]
 [0 0 8 0 0 0 6 0 3]
 [0 9 0 0 7 0 8 3 0]
 [8 1 0 0 6 0 7 4 5]
 [3 0 7 8 4 0 1 9 0]
 [0 0 0 0 5 4 3 7 8]
 [5 8 0 0 3 0 0 2 9]
 [0 0 0 2 8 0 5 0 0]]

[[0 3 0 7 0 6 9 8 4]
 [0 0 6 3 0 0 2 0 7]
 [0 0 8 0 0 0 6 0 3]
 [0 9 0 0 7 0 8 3 0]
 [8 1 0 0 6 0 7 4 5]
 [3 0 7 8 4 0 1 9 0]
 [0 0 0 0 5 4 3 7 8]
 [5 8 0 0 3 0 0 2 9]
 [0 0 0 2 8 0 5 0 0]]

In [3]:
original_grid = np.array([[0, 3, 0, 7, 0, 6, 0, 8, 0],
                        [0, 0, 6, 3, 0, 0, 2, 0, 7],
                        [0, 0, 8, 0, 0, 0, 6, 0, 3],
                        [0, 9, 0, 0, 7, 0, 8, 3, 0],
                        [8, 1, 0, 0, 6, 0, 0, 4, 5],
                        [3, 0, 7, 8, 4, 0, 1, 9, 0],
                        [0, 0, 0, 0, 5, 4, 3, 7, 0],
                        [5, 8, 0, 0, 3, 0, 0, 2, 9],
                        [0, 0, 0, 2, 8, 0, 5, 0, 0]])

In [4]:
def create_list_of_squares(grid):
    list_of_squares = []
    start_row, end_row = 0, 3

    for i in range(3):
        start_col, end_col = 0, 3

        for j in range(3):
            list_of_squares.append(grid[start_row:end_row, start_col:end_col])
            start_col += 3
            end_col += 3
            
        start_row += 3
        end_row += 3

    return list_of_squares

In [5]:
list_of_squares = create_list_of_squares(original_grid)

In [6]:
def return_correct_square(i, j):
    if i < 3 and j < 3:
        return 0
    elif i < 3 and j < 6:
        return 1
    elif i < 3 and j < 9:
        return 2

    elif i < 6 and j < 3:
        return 3
    elif i < 6 and j < 6:
        return 4
    elif i < 6 and j < 9:
        return 5
    
    elif i < 9 and j < 3:
        return 6
    elif i < 9 and j < 6:
        return 7
    elif i < 9 and j < 9:
        return 8

In [7]:
def find_adjacent_rows_and_cols(grid, i, j):
    if i in [0, 3, 6]:
        row_1, row_2 = (grid[i + 1], grid[i + 2])
    elif i in [1, 4, 7]:
        row_1, row_2 = (grid[i - 1], grid[i + 1])
    elif i in [2, 5, 8]:
        row_1, row_2 = (grid[i - 1], grid[i -2])

    if j in [0, 3, 6]:
        col_1, col_2 = (grid.T[j + 1], grid.T[j + 2])
    elif j in [1, 4, 7]:
        col_1, col_2 = (grid.T[j - 1], grid.T[j + 1])
    elif j in [2, 5, 8]:
        col_1, col_2 = (grid.T[j - 1], grid.T[j - 2])

    #---------------

    if j in [0, 1, 2]:
        in_1 = row_1[:3]
        out_1 = row_1[3:]
        in_2 = row_2[:3]
        out_2 = row_2[3:]
    elif j in [3, 4, 5]:
        in_1 = row_1[3:6]
        out_1 = np.concatenate((row_1[:3], row_1[6:]))
        in_2 = row_2[3:6]
        out_2 = np.concatenate((row_2[:3], row_2[6:]))
    elif j in [6, 7, 8]:
        in_1 = row_1[6:]
        out_1 = row_1[:6]
        in_2 = row_2[6:]
        out_2 = row_2[:6]


    if i in [0, 1, 2]:
        in_3 = col_1[:3]
        out_3 = col_1[3:]
        in_4 = col_2[:3]
        out_4 = col_2[3:]
    elif i in [3, 4, 5]:
        in_3 = col_1[3:6]
        out_3 = np.concatenate((col_1[:3], col_1[6:]))
        in_4 = col_2[3:6]
        out_4 = np.concatenate((col_2[:3], col_2[6:]))
    elif i in [6, 7, 8]:
        in_3 = col_1[6:]
        out_3 = col_1[:6]
        in_4 = col_2[6:]
        out_4 = col_2[:6]
    
    return (in_1, in_2, in_3, in_4), (out_1, out_2, out_3, out_4)

In [8]:
original_grid

array([[0, 3, 0, 7, 0, 6, 0, 8, 0],
       [0, 0, 6, 3, 0, 0, 2, 0, 7],
       [0, 0, 8, 0, 0, 0, 6, 0, 3],
       [0, 9, 0, 0, 7, 0, 8, 3, 0],
       [8, 1, 0, 0, 6, 0, 0, 4, 5],
       [3, 0, 7, 8, 4, 0, 1, 9, 0],
       [0, 0, 0, 0, 5, 4, 3, 7, 0],
       [5, 8, 0, 0, 3, 0, 0, 2, 9],
       [0, 0, 0, 2, 8, 0, 5, 0, 0]])

In [9]:
in_, out = find_adjacent_rows_and_cols(original_grid, 4, 4)
print(in_, out)

(array([0, 7, 0]), array([8, 4, 0]), array([0, 0, 8]), array([0, 0, 0])) (array([0, 9, 0, 8, 3, 0]), array([3, 0, 7, 1, 9, 0]), array([7, 3, 0, 0, 0, 2]), array([6, 0, 0, 4, 0, 0]))


In [44]:
test[:6]

array([0, 0, 6, 3, 0, 0])

In [41]:
np.concatenate((test[:3], test[6:]))

array([0, 0, 6, 2, 0, 7])

In [9]:
# Remplacer une valeur dans un carré

test = list_of_squares[return_correct_square(3, 6)].copy()
print(test)
mask = (test == 0)
coordinates = np.argwhere(mask).tolist()
print(coordinates)

for coor in coordinates:
    test[coor[0], coor[1]] = 10

print(test)

[[8 3 0]
 [0 4 5]
 [1 9 0]]
[[0, 2], [1, 0], [2, 2]]
[[ 8  3 10]
 [10  4  5]
 [ 1  9 10]]


In [10]:
(arr1 == arr2).all(axis=1)

NameError: name 'arr1' is not defined

In [20]:
# Premier tableau
arr1 = np.array([[0, 0, 0],
                 [0, 0, 6],
                 [0, 0, 8]])

arr2 = np.array([0, 0, 0])
arr2 = np.reshape(arr2, (-1, 1))

axis = 0

indices = np.where((arr1 == arr2).all(axis=axis))[0]
print(indices)

print((arr1 == arr2).all(axis=axis))

[0 1]
[ True  True False]


In [12]:
np.any((arr1 == arr2).all(axis=0))

True

In [14]:
import numpy as np

# Premier tableau
arr1 = np.array([[0, 3, 0],
                 [0, 0, 6],
                 [0, 0, 8]])

# Deuxième tableau
arr2 = np.array([0, 0, 6])

# Recherche de l'index de la ligne correspondante
indices = np.where((arr1 == arr2).all(axis=1))[0]
print(indices)

if indices.size > 0:
    index_ligne = indices[0]
    print("Le deuxième tableau correspond à la ligne", index_ligne+1, "du premier tableau.")
else:
    print("Aucune ligne du premier tableau ne correspond au deuxième tableau.")


[1]
Le deuxième tableau correspond à la ligne 2 du premier tableau.


In [14]:
arr1 = np.array([[0, 3, 0],
                 [0, 0, 6],
                 [0, 0, 8]])

(arr1 == 0).sum()

6

In [21]:
create_list_of_squares(original_grid)

[array([[0, 3, 0],
        [0, 0, 6],
        [0, 0, 8]]),
 array([[7, 0, 6],
        [3, 0, 0],
        [0, 0, 0]]),
 array([[0, 8, 0],
        [2, 0, 7],
        [6, 0, 3]]),
 array([[0, 9, 0],
        [8, 1, 0],
        [3, 0, 7]]),
 array([[0, 7, 0],
        [0, 6, 0],
        [8, 4, 0]]),
 array([[8, 3, 0],
        [0, 4, 5],
        [1, 9, 0]]),
 array([[0, 0, 0],
        [5, 8, 0],
        [0, 0, 0]]),
 array([[0, 5, 4],
        [0, 3, 0],
        [2, 8, 0]]),
 array([[3, 7, 0],
        [0, 2, 9],
        [5, 0, 0]])]

In [24]:
grid = original_grid.copy()

for _ in range(2):
    for i in range(9):
        for j in range(9):
            number_value = grid[i, j]
            coordinates = (i, j)

            actual_row = grid[i]
            actual_column = grid.T[j]
            #-- ?
            #list_of_squares = create_list_of_squares(grid)
            #actual_square = list_of_squares[return_correct_square(i, j)]
            

            #--

            
            #[print(a, b) for a, b  in zip(square_rows_and_cols, out_of_square_rows_and_cols)]
            

            # To implement :
            if number_value == 0:
                
                list_of_squares = create_list_of_squares(grid)
                actual_square = list_of_squares[return_correct_square(i, j)]
                print(f"Valeur : {number_value} en position {coordinates}")
                print(actual_row, actual_column)
                print(actual_square)

                for k in range(1, 10):
                    
                    actual_square_copy = actual_square.copy()
                    in_square, out_square = find_adjacent_rows_and_cols(grid, i, j)
                    #square_rows_and_cols = [adjacent_row_and_col[:3] for adjacent_row_and_col in adjacent_rows_and_cols]
                    #out_of_square_rows_and_cols = [adjacent_row_and_col[3:] for adjacent_row_and_col in adjacent_rows_and_cols]

                    for idx, in_out_square in enumerate(zip(in_square, out_square)):
                        in_square, out_square = in_out_square
                        print(f"k = {k}")
                        print(idx)
                        print(in_square, out_square, i, j)
                        if (k in out_square) and (k not in actual_square_copy):
                            in_square_copy = in_square.copy()
                            #print(coordinates)
                            #print(f"k = {k} in square : {in_square_copy} out square : {out_square}")

                            if idx in [0, 1]:
                                axis = 1
                                indices = np.where((actual_square_copy == in_square_copy).all(axis=axis))[0]
                                if len(indices) > 1:
                                    continue
                                #print(actual_square_copy[indices])
                                actual_square_copy[indices] = 42
                            elif idx in [2, 3]:
                                in_square_copy = np.reshape(in_square_copy, (-1, 1))
                                axis = 0
                                indices = np.where((actual_square_copy == in_square_copy).all(axis=axis))[0]
                                if len(indices) > 1:
                                    continue
                                #print(actual_square_copy[:, indices])
                                actual_square_copy[:, indices] = 42

                    #print(actual_square_copy)
                    if ((actual_square_copy == 0).sum() == 1) and (k not in actual_square):
                        print(f"I replace value {grid[i, j]} in position {coordinates} with value {k}")
                        grid[i, j] = k
                        break
            #[print(a, b) for a, b  in zip(square_rows_and_cols, out_of_square_rows_and_cols)]
            print('-'*20)
    print(grid)
                    



Valeur : 0 en position (0, 0)
[0 3 0 7 0 6 0 8 0] [0 0 0 0 8 3 0 5 0]
[[0 3 0]
 [0 0 6]
 [0 0 8]]
k = 1
0
[0 0 6] [3 0 0 2 0 7] 0 0
k = 1
1
[0 0 8] [0 0 0 6 0 3] 0 0
k = 1
2
[3 0 0] [9 1 0 0 8 0] 0 0
k = 1
3
[0 6 8] [0 0 7 0 0 0] 0 0
k = 2
0
[0 0 6] [3 0 0 2 0 7] 0 0
k = 2
1
[0 0 8] [0 0 0 6 0 3] 0 0
k = 2
2
[3 0 0] [9 1 0 0 8 0] 0 0
k = 2
3
[0 6 8] [0 0 7 0 0 0] 0 0
k = 3
0
[0 0 6] [3 0 0 2 0 7] 0 0
k = 3
1
[0 0 8] [0 0 0 6 0 3] 0 0
k = 3
2
[3 0 0] [9 1 0 0 8 0] 0 0
k = 3
3
[0 6 8] [0 0 7 0 0 0] 0 0
k = 4
0
[0 0 6] [3 0 0 2 0 7] 0 0
k = 4
1
[0 0 8] [0 0 0 6 0 3] 0 0
k = 4
2
[3 0 0] [9 1 0 0 8 0] 0 0
k = 4
3
[0 6 8] [0 0 7 0 0 0] 0 0
k = 5
0
[0 0 6] [3 0 0 2 0 7] 0 0
k = 5
1
[0 0 8] [0 0 0 6 0 3] 0 0
k = 5
2
[3 0 0] [9 1 0 0 8 0] 0 0
k = 5
3
[0 6 8] [0 0 7 0 0 0] 0 0
k = 6
0
[0 0 6] [3 0 0 2 0 7] 0 0
k = 6
1
[0 0 8] [0 0 0 6 0 3] 0 0
k = 6
2
[3 0 0] [9 1 0 0 8 0] 0 0
k = 6
3
[0 6 8] [0 0 7 0 0 0] 0 0
k = 7
0
[0 0 6] [3 0 0 2 0 7] 0 0
k = 7
1
[0 0 8] [0 0 0 6 0 3] 0 0
k = 7
2
[3 0 0] [9

In [85]:
grid

array([[0, 3, 0, 7, 0, 6, 9, 8, 4],
       [0, 0, 6, 3, 0, 0, 2, 0, 7],
       [0, 0, 8, 4, 0, 0, 6, 0, 3],
       [0, 9, 0, 0, 7, 0, 8, 3, 0],
       [8, 1, 0, 0, 6, 0, 0, 4, 5],
       [3, 0, 7, 8, 4, 0, 1, 9, 0],
       [0, 0, 0, 0, 5, 4, 3, 7, 0],
       [5, 8, 2, 0, 3, 0, 0, 2, 9],
       [0, 0, 0, 2, 8, 0, 5, 0, 0]])

In [86]:
1+1

2

In [84]:
original_grid

array([[0, 3, 0, 7, 0, 6, 0, 8, 0],
       [0, 0, 6, 3, 0, 0, 2, 0, 7],
       [0, 0, 8, 0, 0, 0, 6, 0, 3],
       [0, 9, 0, 0, 7, 0, 8, 3, 0],
       [8, 1, 0, 0, 6, 0, 0, 4, 5],
       [3, 0, 7, 8, 4, 0, 1, 9, 0],
       [0, 0, 0, 0, 5, 4, 3, 7, 0],
       [5, 8, 0, 0, 3, 0, 0, 2, 9],
       [0, 0, 0, 2, 8, 0, 5, 0, 0]])

In [10]:
grid = original_grid.copy()

for i in range(1):
    for j in range(1):
        number_value = grid[i, j]
        coordinates = (i, j)

        actual_row = grid[i]
        actual_column = grid.T[j]
        list_of_squares = create_list_of_squares(grid)
        actual_square = list_of_squares[return_correct_square(i, j)]

        adjacent_rows_and_cols = find_adjacent_rows_and_cols(grid, i, j)
        square_rows_and_cols = [adjacent_row_and_col[:3] for adjacent_row_and_col in adjacent_rows_and_cols]
        out_of_square_rows_and_cols = [adjacent_row_and_col[3:] for adjacent_row_and_col in adjacent_rows_and_cols]

        print(f"Valeur : {number_value} en position {coordinates}")
        print(actual_row, actual_column)
        print(actual_square)
        [print(a, b) for a, b  in zip(square_rows_and_cols, out_of_square_rows_and_cols)]
        print('-'*20)

        # To implement :
        if number_value == 0:
            for k in range(1, 10):
                actual_square_copy = actual_square.copy() #use this line instead ?

                result_list = []
                for in_square, out_square in zip(square_rows_and_cols, out_of_square_rows_and_cols):
                    if k in out_square:
                        in_square_copy = in_square.copy()
                        mask = (in_square_copy == 0)
                        coordinates = np.argwhere(mask).tolist()
                        #print(coordinates)
                        print(f"k = {k} in square : {in_square_copy} out square : {out_square}")
                        for coor in coordinates:
                            in_square_copy[coor[0]] = 42
                        result_list.append(in_square_copy)
                    else:
                        result_list.append(in_square)

                print(result_list)
                
                if 0 not in np.vstack(result_list):
                    grid[i, j] = k




Valeur : 0 en position (0, 0)
[0 3 0 7 0 6 0 8 0] [0 0 0 0 8 3 0 5 0]
[[0 3 0]
 [0 0 6]
 [0 0 8]]
[0 0 6] [3 0 0 2 0 7]
[0 0 8] [0 0 0 6 0 3]
[3 0 0] [9 1 0 0 8 0]
[0 6 8] [0 0 7 0 0 0]
--------------------
k = 1 in square : [3 0 0] out square : [9 1 0 0 8 0]
[array([0, 0, 6]), array([0, 0, 8]), array([ 3, 42, 42]), array([0, 6, 8])]
k = 2 in square : [0 0 6] out square : [3 0 0 2 0 7]
[array([42, 42,  6]), array([0, 0, 8]), array([3, 0, 0]), array([0, 6, 8])]
k = 3 in square : [0 0 6] out square : [3 0 0 2 0 7]
k = 3 in square : [0 0 8] out square : [0 0 0 6 0 3]
[array([42, 42,  6]), array([42, 42,  8]), array([3, 0, 0]), array([0, 6, 8])]
[array([0, 0, 6]), array([0, 0, 8]), array([3, 0, 0]), array([0, 6, 8])]
[array([0, 0, 6]), array([0, 0, 8]), array([3, 0, 0]), array([0, 6, 8])]
k = 6 in square : [0 0 8] out square : [0 0 0 6 0 3]
[array([0, 0, 6]), array([42, 42,  8]), array([3, 0, 0]), array([0, 6, 8])]
k = 7 in square : [0 0 6] out square : [3 0 0 2 0 7]
k = 7 in square : [0 6

In [68]:
carre = np.array([[0, 3, 0],
                    [0, 0, 6],
                    [0, 0, 8]])

search = np.array([0, 0, 6])
search = [0, 0, 6]

In [73]:
carre[1] == search

array([ True,  True,  True])

In [54]:
search

array([0, 0, 6])

In [29]:
original_grid

array([[0, 3, 0, 7, 0, 6, 0, 8, 0],
       [0, 0, 6, 3, 0, 0, 2, 0, 7],
       [0, 0, 8, 0, 0, 0, 6, 0, 3],
       [0, 9, 0, 0, 7, 0, 8, 3, 0],
       [8, 1, 0, 0, 6, 0, 0, 4, 5],
       [3, 0, 7, 8, 4, 0, 1, 9, 0],
       [0, 0, 0, 0, 5, 4, 3, 7, 0],
       [5, 8, 0, 0, 3, 0, 0, 2, 9],
       [0, 0, 0, 2, 8, 0, 5, 0, 0]])

In [41]:
test = [np.array([42, 42, 6]), np.array([42, 42, 8]), np.array([ 3, 42, 42]), np.array([42, 6, 8])]
print(test)

update_value = False
for elt in test:
    if 0 not in elt:
        update_value = True

print(update_value)

[array([42, 42,  6]), array([42, 42,  8]), array([ 3, 42, 42]), array([42,  6,  8])]
True


In [46]:
print(np.vstack(test))
0 not in np.vstack(test)

[[42 42  6]
 [42 42  8]
 [ 3 42 42]
 [42  6  8]]


True

In [14]:
grid = original_grid.copy()

for i in range(9):
    for j in range(9):
        number_value = grid[i, j]
        coordinates = (i, j)

        actual_row = grid[i]
        actual_column = grid.T[j]
        actual_square = list_of_squares[return_correct_square(i, j)]

        adjacent_rows = adjacent_rows_and_cols(i, j)[0:2]
        adjacent_cols = adjacent_rows_and_cols(i, j)[2:4]
        square_rows = [adjacent_row[:3] for adjacent_row in adjacent_rows]
        square_cols = [adjacent_col[:3] for adjacent_col in adjacent_cols]
        print(square_cols)

        print(f"Valeur : {number_value} en position {coordinates}")
        print(actual_row, actual_column)
        print(actual_square)
        print(adjacent_rows, adjacent_cols)
        print(adjacent_rows[0][3:], adjacent_rows[1][3:], adjacent_cols[0][3:], adjacent_cols[1][3:])
        print('-'*20)

        # To implement :
        #if number_value == 0:
        #    for k in range(1, 10):
        #        print(k)
        #        mask_square = actual_square.copy()

[array([3, 0, 0]), array([0, 6, 8])]
Valeur : 0 en position (0, 0)
[0 3 0 7 0 6 0 8 0] [0 0 0 0 8 3 0 5 0]
[[0 3 0]
 [0 0 6]
 [0 0 8]]
(array([0, 0, 6, 3, 0, 0, 2, 0, 7]), array([0, 0, 8, 0, 0, 0, 6, 0, 3])) (array([3, 0, 0, 9, 1, 0, 0, 8, 0]), array([0, 6, 8, 0, 0, 7, 0, 0, 0]))
[3 0 0 2 0 7] [0 0 0 6 0 3] [9 1 0 0 8 0] [0 0 7 0 0 0]
--------------------
[array([0, 0, 0]), array([0, 6, 8])]
Valeur : 3 en position (0, 1)
[0 3 0 7 0 6 0 8 0] [3 0 0 9 1 0 0 8 0]
[[0 3 0]
 [0 0 6]
 [0 0 8]]
(array([0, 0, 6, 3, 0, 0, 2, 0, 7]), array([0, 0, 8, 0, 0, 0, 6, 0, 3])) (array([0, 0, 0, 0, 8, 3, 0, 5, 0]), array([0, 6, 8, 0, 0, 7, 0, 0, 0]))
[3 0 0 2 0 7] [0 0 0 6 0 3] [0 8 3 0 5 0] [0 0 7 0 0 0]
--------------------
[array([3, 0, 0]), array([0, 0, 0])]
Valeur : 0 en position (0, 2)
[0 3 0 7 0 6 0 8 0] [0 6 8 0 0 7 0 0 0]
[[0 3 0]
 [0 0 6]
 [0 0 8]]
(array([0, 0, 6, 3, 0, 0, 2, 0, 7]), array([0, 0, 8, 0, 0, 0, 6, 0, 3])) (array([3, 0, 0, 9, 1, 0, 0, 8, 0]), array([0, 0, 0, 0, 8, 3, 0, 5, 0]))
[3 

In [61]:
for i in range(3):
    for j in range(3):
        print(list_of_squares[0][i, j])

0
3
0
0
0
6
0
0
8


In [57]:
for i in range(1): # change to 9
 print(list_of_squares[i])

[[0 3 0]
 [0 0 6]
 [0 0 8]]


In [35]:
grid[3:6, 0:3]

array([[1, 2, 6],
       [4, 6, 1],
       [4, 1, 8]])

In [19]:
grid[0]

array([7, 6, 5, 6, 9, 9, 3, 4, 3])

In [11]:
grid.T[0]

array([7, 7, 3, 1, 4, 4, 3, 1, 9])

In [53]:
while 0 in grid:

True